# Generated by Django 2.2.4 on 2019-09-29 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20190929_0014'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Proudct',
            new_name='Product',
        ),
    ]
