# Generated by Django 2.2.4 on 2019-10-01 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20191001_1505'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerQuery',
            fields=[
                ('query_id', models.AutoField(primary_key=True, serialize=False)),
                ('cust_name', models.CharField(default='', max_length=100)),
                ('cust_phone', models.CharField(default='0', max_length=20)),
                ('cust_query', models.CharField(default='', max_length=5000)),
                ('cust_email', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
